# Generated by Django 2.2.6 on 2019-12-11 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citasmedicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citasmedicas.especialidad'),
        ),
    ]
